apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: token-tjeneste
  namespace: helsearbeidsgiver
spec:
  ingresses:
    {{#each ingresses as |url|}}
      - {{ url }}
    {{/each}}
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  secureLogs:
    enabled: true