apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: token-tjeneste
  namespace: team-esyfo
spec:
  ingresses:
    - https://esyfo-token.intern.dev.nav.no
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  accessPolicy:
    outbound:
      external:
        - host: test.maskinporten.no
  env:
    - name: MASKINPORTEN_TOKEN_ENDPOINT
      value: "https://test.maskinporten.no/token"
    - name: MASKINPORTEN_CLIENT_ISSUER
      value: "https://test.maskinporten.no/"
  envFrom:
    - secret: maskinporten-secrets
